<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>XV.Comms</RootNamespace>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="..\XV.Core\XV.Core.csproj" /></ItemGroup>
</Project>
